# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [325]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [327]:
A = np.arange(1, 16).reshape(3,5)

In [329]:
print(A)
print(f'Dimensions: {A.ndim}')
print(f'Shape: {A.shape}')
print(f'Size: {A.size}')
print(f'Datatype: {type(A)}')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimensions: 2
Shape: (3, 5)
Size: 15
Datatype: <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [331]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [333]:
print(B - C,'\n')
print(B * C,'\n')
print(C * B,'\n')    # To show that elementwise multiplication is commutative 
print(B @ C,'\n')
print(C @ B,'\n')    # To show that matrix multiplication is NOT commutative 

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]] 

[[24. 30. 36.]
 [24. 30. 36.]
 [24. 30. 36.]] 



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [335]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [337]:
print(np.exp(B))
print(B.min())
print(B.min(axis=1))
print(B.min(axis=0))
print(np.argmin(B))
print(np.argmin(B,axis=1))
print(B.sum())
print(B.mean(axis=0))
print(np.median(B,axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [339]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [341]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Den tar alla element i den dimension som utelämnas. I detta fall tar den 2:a raden (eftersom index börjar på 0) och sedan elementen i samtliga kolumner i den raden. Kan även skrivas A[1,:] där då : visar alla element. För att få alla elemen i andra kolumnen istället kan man skriva A[:,1]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [343]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [345]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [347]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [349]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Först skapas en radvektor (a) med 30 element i nummerföljd från 0 till 29. Sedan skapas en tensor av ordning 3 (b) genom att omforma (a). Det blir lite slarvigt uttryckt en matris i 3 dimensioner - 2 rader, 3 kolumner och 2 i ytterligare en riktning (vi kan se det som djupet i ett rätblock). 

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [351]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [353]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [355]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [357]:
def add_mult_matrices(A, B, operation):
    # Ensure both inputs are NumPy arrays
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise TypeError('Only NumPy arrays are allowed')

    # Ensure the operation is a string
    if not isinstance(operation, str):
        raise ValueError('Operation must be a string')

    # Handle Matrix addition
    if operation.lower() == 'add':
        if A.shape != B.shape:
            raise ValueError('The dimensions of the arrays must match for addition')
        return A + B

    # Handle Matrix multiplication 
    elif operation.lower() == 'multiply':
        if A.ndim == 1:
            A = A.reshape(1, -1)    # Convert a 1D matrix to 2D because multiplication isn't defined for 1D matrices

        if B.ndim == 1:
            B = B.reshape(1, -1)    # Convert a 1D matrix to 2D because multiplication isn't defined for 1D matrices

        if A.shape[1] != B.shape[0]:
            raise ValueError('The number of columns in the first array mut match match the number of rows in the second array')
        return A @ B
    else:
        raise ValueError('Invalid operation. Only "add" and "multiply" are allowed')

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [359]:
print('Uppgift 10.1.1')
x = np.array([[4, 3]])
print(f'a) {x.shape}')
print(f'b) {5 * x}')
print(f'c) {3 * x}')
print(f'd) {5*x + 3*x}')
print(f'e) {8 * x}')
print(f'f) {4*x - x}')
print(f'g) {x.T}')
print(f'dimension {x.T.shape}')
print('h) Nej, eftersom dimensionerna hos de två vektorerna inte matchar')
print(f'i) {np.linalg.norm(x)}')         # Det går också med t.ex. np.sqrt(np.sum(x ** 2))

print('\n Uppgift 10.1.2')
v = np.array([[3],[7],[0],[11]])
print(f'a) {v.shape}')
print(f'b) {2 * v}')
print(f'c) {5*v + 2*v}')
print(f'd) {4*v - 2*v}')
print(f'e) {v.T}')
print(f'dimension {v.T.shape}')
print(f'f) {np.linalg.norm(v)}')

print('\n Uppgift 10.1.3')
v1 = np.array([[4, 3, 1, 5]])
v2 = np.array([[2, 3, 1, 1]])
print(f'a) {np.linalg.norm(v1)}')
print(f'a) {np.linalg.norm(v1 - v2)}')




Uppgift 10.1.1
a) (1, 2)
b) [[20 15]]
c) [[12  9]]
d) [[32 24]]
e) [[32 24]]
f) [[12  9]]
g) [[4]
 [3]]
dimension (2, 1)
h) Nej, eftersom dimensionerna hos de två vektorerna inte matchar
i) 5.0

 Uppgift 10.1.2
a) (4, 1)
b) [[ 6]
 [14]
 [ 0]
 [22]]
c) [[21]
 [49]
 [ 0]
 [77]]
d) [[ 6]
 [14]
 [ 0]
 [22]]
e) [[ 3  7  0 11]]
dimension (1, 4)
f) 13.379088160259652

 Uppgift 10.1.3
a) 7.14142842854285
a) 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [361]:
print('Uppgift 10.2.1')
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

print(f'a) {2 * A}')
print(f'b) {B - 2*A}')
print(f'c) Ej definierat ty dimensionerna på C och E är icke lika')
print(f'd) {2*D - 3*C}')
print(f'e) {D.T + 2*D}')
print(f'f) {2*C.T - 2*D.T}')
print(f'g) Ej definierat ty när A transponeras ändras dess dimensioner och matchar då inte B:s')
print(f'h) Ej definierat ty antal kolumner i A (3 st) är ej lika med antal rader i C (2 st)')
print(f'i) {add_mult_matrices(C, D, 'multiply')}')
print(f'j) {add_mult_matrices(C, B, 'multiply')}')
print(f'i) {add_mult_matrices(C, I, 'multiply')}')
print(f'i) {add_mult_matrices(A, B.T, 'multiply')}')

print('\n Uppgift 10.2.2')
A = np.array([[2, 3, 4], [5, 4, 1]])
print(f'a) {add_mult_matrices(A, A.T, 'multiply')}')

print('\n Uppgift 10.2.3')
A = np.array([[1, 2], [2, 4]]) 
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])
print(f'AB = \n {add_mult_matrices(A, B, 'multiply')}')
print(f'AC = \n {add_mult_matrices(A, C, 'multiply')}')

if np.all(add_mult_matrices(A, B, 'multiply') == add_mult_matrices(A, C, 'multiply')):
    print('AB = AC')
else:
    print('AB != AC')

if np.all(B == C):
    print('AB = AC')
else:
    print('B != C')

Uppgift 10.2.1
a) [[ 4  2 -2]
 [ 2 -2  2]]
b) [[ 0 -4  3]
 [ 0 -2 -4]]
c) Ej definierat ty dimensionerna på C och E är icke lika
d) [[3 2]
 [2 3]]
e) [[ 9 12]
 [12  9]]
f) [[-4 -4]
 [-4 -4]]
g) Ej definierat ty när A transponeras ändras dess dimensioner och matchar då inte B:s
h) Ej definierat ty antal kolumner i A (3 st) är ej lika med antal rader i C (2 st)
i) [[11 10]
 [10 11]]
j) [[  8 -10  -3]
 [ 10  -8   0]]
i) [[1 2]
 [2 1]]
i) [[5 2]
 [7 4]]

 Uppgift 10.2.2
a) [[29 26]
 [26 42]]

 Uppgift 10.2.3
AB = 
 [[ 4  7]
 [ 8 14]]
AC = 
 [[ 4  7]
 [ 8 14]]
AB = AC
B != C


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [363]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [365]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [367]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


You can check if an array is a view or copy with .base. It returns the copy if it is a view. If it is a copy it retuns None. 
v2 is a view of v1 so when you make changes in v1 the reflects in v2. 